name: "Run PyTest Unit Tests"

on:
  pull_request:
    branches:
      - "main"

jobs:
  RunUnitTests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4.1.6

      - name: "Install Python Dependencies"
        run: "pip3 install -r requirements.txt"

      - name: "Run Unit Tests"
        run: "python3 -m pytest tests/"
